<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "posts".
 *
 * @property int $id
 * @property string $title
 * @property string $description
 * @property string $encoded
 * @property string $video_url
 * @property string $price
 * @property string $secret_key
 * @property string $golos_permlink
 * @property string $golos_parentPermlink
 * @property int $not_encrypted
 * @property int $user_id
 */
class Posts extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'posts';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['description', 'encoded'], 'string'],
            [['price'], 'number'],
            [['not_encrypted'], 'integer'],
            [['title'], 'string', 'max' => 256],
            [['video_url', 'secret_key', 'golos_permlink'], 'string', 'max' => 512],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'description' => 'Description',
            'encoded' => 'Encoded',
            'video_url' => 'Video Url',
            'price' => 'Price',
            'secret_key' => 'Secret Key',
            'golos_permlink' => 'Golos Permlink',
            'not_encrypted' => 'Not Encrypted',
        ];
    }

    public function beforeSave($insert)
    {
        if($insert) {

        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public function getAuthor()
    {
        return self::hasOne(Users::className(), ['id' => 'user_id']);
    }

}
